services:
  - type: web
    name: aza
    runtime: docker
    plan: free
    envVars:
      - key: APP_NAME
        value: "AZA Electromechanical"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://aza.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-1-eu-central-1.pooler.supabase.com
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.rmckgxgiqjuvjeziskdr
      - key: DB_PASSWORD
        sync: false
      - key: FILESYSTEM_DISK
        value: public
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
